name             'hpf'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures hpf'
long_description 'Installs/Configures hpf'
version          '0.1.0'

depends 'apache2'
depends 'nodejs'
depends 'git'